version: "3.9"

x-logging: &logging-conf
  driver: json-file
  options:
    max-size: '10m'
    max-file: '10'

services:
  # kong:
  #   image: kong/kong-gateway:3.2.2.1
  #   user: kong
  #   container_name: kong-gateway
  #   environment:
  #     KONG_DATABASE: "off"
  #     KONG_ADMIN_GUI_PATH:  /manager
  #     KONG_ADMIN_GUI_URL: http://localhost:8002/manager
  #     KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #   volumes:
  #     - ./kong.yaml:/kong/declarative/kong.yml
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #     - 8002:8002
  #   networks:
  #     kong-net:
  #       ipv4_address: 160.160.160.10


  kong:
    image: kong/kong-gateway:3.2.2.1
    container_name: kong-gateway
    profiles: ["kong"]
    logging: *logging-conf
    environment:
      KONG_LICENSE_DATA: ""
      # On real/production configuration screets should be stored here
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: 190.190.10.11
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      # KONG_PROXY_ACCESS_LOG: /usr/local/kong/logs/kong/proxy_access.log
      # KONG_PROXY_ERROR_LOG: /usr/local/kong/logs/kong/proxy_error.log
      # KONG_ADMIN_ACCESS_LOG: /dev/stdout
      # KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./config/kong.conf:/etc/kong/kong.conf:ro
      - ./logs:/home/kong/logs
    ports:
      - 8000:8000 # proxy http
      - 8001:8001 # admin http
      # - 8444:8444 # admin https/ssl
      - 8002:8002 # admin UI
    networks:
      kong-net:
        ipv4_address: 190.190.10.10
    depends_on:
      - db
    restart: on-failure:5

  db:
    image: postgres:13
    container_name: postgres-13
    profiles: ['db']
    logging: *logging-conf
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
      POSTGRES_DB: kong
    ports: 
      - 5432:5432
    networks:
      kong-net:
        ipv4_address: 190.190.10.11
    volumes:
      - kong-data:/var/lib/postgresql/data
    restart: on-failure:5




networks:
  kong-net:
    name: kong-net
    ipam:
      driver: default
      config:
        - subnet: 190.190.10.0/24

volumes:
  kong-data:
    name: "kong-gateway-postgres-data"
    driver: local


#########
## Shell command to migrate kong configuration into PostGres
#########
# docker run --rm \
#      -e "KONG_DATABASE=postgres" \
#      -e "KONG_PG_HOST=10.10.25.93" \
#      -e "KONG_PG_USER=kong" \
#      -e "KONG_PG_PASSWORD=kongpass" \
#      kong/kong-gateway:3.2.2.1 kong migrations bootstrap

